name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --verbose -- --check
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Build
      run: |
          cargo version
          rustc --version
          cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cargo version
          rustc --version
          cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cargo version
          rustc --version
          cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
